"""replace uuid with int

Revision ID: 56ca3c7d3b36
Revises: 548c0117c4d5
Create Date: 2024-03-03 16:53:01.500811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ca3c7d3b36'
down_revision: Union[str, None] = '548c0117c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potion_ingredient',
    sa.Column('potion_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.pk'], ),
    sa.ForeignKeyConstraint(['potion_id'], ['potion.pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potion_ingredient')
    # ### end Alembic commands ###
